// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTjqd9GjBW1xVm-Kq10Q7IFeKU4eloYK4',
    appId: '1:123521211470:web:1ae8337b6f73f1d3f5371f',
    messagingSenderId: '123521211470',
    projectId: 'akilli-kampus-proje',
    authDomain: 'akilli-kampus-proje.firebaseapp.com',
    storageBucket: 'akilli-kampus-proje.firebasestorage.app',
    measurementId: 'G-QWTQHEKGBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsIsUOFWwcoooCtmyRftJLJFalyVnJPFU',
    appId: '1:123521211470:android:3ee3a6e30f6cbd41f5371f',
    messagingSenderId: '123521211470',
    projectId: 'akilli-kampus-proje',
    storageBucket: 'akilli-kampus-proje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYpYfL7qmP_bg3n4q7M3Au57pgW92wazc',
    appId: '1:123521211470:ios:b4a4ce55d952c5adf5371f',
    messagingSenderId: '123521211470',
    projectId: 'akilli-kampus-proje',
    storageBucket: 'akilli-kampus-proje.firebasestorage.app',
    iosBundleId: 'com.mustafa.akilliKampusProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYpYfL7qmP_bg3n4q7M3Au57pgW92wazc',
    appId: '1:123521211470:ios:b4a4ce55d952c5adf5371f',
    messagingSenderId: '123521211470',
    projectId: 'akilli-kampus-proje',
    storageBucket: 'akilli-kampus-proje.firebasestorage.app',
    iosBundleId: 'com.mustafa.akilliKampusProje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTjqd9GjBW1xVm-Kq10Q7IFeKU4eloYK4',
    appId: '1:123521211470:web:6e258f5547ee4fa2f5371f',
    messagingSenderId: '123521211470',
    projectId: 'akilli-kampus-proje',
    authDomain: 'akilli-kampus-proje.firebaseapp.com',
    storageBucket: 'akilli-kampus-proje.firebasestorage.app',
    measurementId: 'G-NN9B3WRSV2',
  );
}
